apiVersion: apps/v1
kind: Deployment
metadata:
  name: simpleweb-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simpleweb
  template:
    metadata:
      labels:
        app: simpleweb
    spec:
      containers:
      - name: simpleweb
        image: hyder/simpleweb:0.0.2
        