apiVersion: apps/v1
kind: Deployment
metadata:

  name: simpleweb-depl
spec:
  selector:
    matchLabels:
      app: simpleweb
  template:
    metadata:
      labels:
        app: simpleweb
    spec:
      containers:
      - name: simpleweb
        image: hyderdevelops/simpleweb:latest
        imagePullPolicy: Never
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
       
